import { useParams, Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const pages: Record<string, { title: string; content: string[] }> = {
  about: {
    title: "About Us",
    content: [
      "ShopSmart was founded with a simple mission: make online shopping smarter, faster, and more enjoyable for everyone.",
      "We leverage cutting-edge technology to provide personalized recommendations, real-time inventory insights, and a seamless checkout experience.",
      "Our team of passionate engineers, designers, and product experts work tirelessly to bring you the best products at the best prices.",
      "Based in San Francisco, we serve millions of customers worldwide and partner with thousands of brands to deliver quality you can trust.",
    ],
  },
  careers: {
    title: "Careers",
    content: [
      "Join the ShopSmart team and help shape the future of e-commerce.",
      "We're always looking for talented individuals who are passionate about technology, design, and customer experience.",
      "We offer competitive salaries, comprehensive benefits, remote-first culture, and opportunities to work on products used by millions.",
      "Check back soon for open positions, or send your resume to careers@shopsmart.com.",
    ],
  },
  blog: {
    title: "Blog",
    content: [
      "Welcome to the ShopSmart Blog — your source for shopping tips, product guides, and industry news.",
      "Stay tuned for our latest articles on trending products, smart shopping strategies, and behind-the-scenes looks at ShopSmart.",
      "New posts are published weekly. Subscribe to our newsletter to never miss an update!",
    ],
  },
  press: {
    title: "Press",
    content: [
      "For media inquiries, please contact press@shopsmart.com.",
      "ShopSmart has been featured in TechCrunch, Forbes, The Verge, and many more publications.",
      "Download our press kit and brand assets for your coverage needs.",
    ],
  },
  sustainability: {
    title: "Sustainability",
    content: [
      "At ShopSmart, sustainability is at the core of everything we do.",
      "We partner with eco-conscious brands, use carbon-neutral shipping options, and minimize packaging waste.",
      "Our goal is to make responsible shopping the default — not an afterthought.",
    ],
  },
  help: {
    title: "Help Center",
    content: [
      "Welcome to the ShopSmart Help Center. Find answers to the most common questions below.",
      "Topics: Orders & Shipping, Returns & Refunds, Account Management, Payment Issues, Technical Support.",
      "Can't find what you're looking for? Contact our support team at support@shopsmart.com or use the Contact Us page.",
    ],
  },
  contact: {
    title: "Contact Us",
    content: [
      "We'd love to hear from you! Reach out to our team using the methods below.",
      "Email: support@shopsmart.com",
      "Phone: 1-800-SHOP-SMART (Mon–Fri, 9am–6pm PST)",
      "Live Chat: Available 24/7 via the chat icon in the bottom-right corner.",
      "Mailing Address: 123 Commerce St, San Francisco, CA 94105",
    ],
  },
  returns: {
    title: "Returns & Refunds",
    content: [
      "We want you to be completely satisfied with your purchase. If you're not, we make returns easy.",
      "Most items can be returned within 30 days of delivery for a full refund.",
      "To start a return, go to My Orders in your profile and select the item you'd like to return.",
      "Refunds are processed within 5–7 business days after we receive the returned item.",
      "Some items (e.g., personalized products, perishables) are non-returnable. Check the product page for details.",
    ],
  },
  "shipping-info": {
    title: "Shipping Information",
    content: [
      "We offer multiple shipping options to meet your needs:",
      "Standard Shipping (5–7 business days): Free on orders over $50, otherwise $4.99.",
      "Express Shipping (2–3 business days): $9.99.",
      "Same-Day Delivery: Available in select metro areas for $14.99.",
      "International shipping is available to 50+ countries. Rates are calculated at checkout.",
    ],
  },
  "gift-cards": {
    title: "Gift Cards",
    content: [
      "Give the gift of choice with a ShopSmart Gift Card.",
      "Available in denominations from $10 to $500. Gift cards never expire and have no fees.",
      "Digital gift cards are delivered instantly via email. Physical cards ship within 1–2 business days.",
      "To redeem, enter your gift card code at checkout.",
    ],
  },
  privacy: {
    title: "Privacy Policy",
    content: [
      "Your privacy matters to us. This policy explains how ShopSmart collects, uses, and protects your personal information.",
      "We collect information you provide (name, email, address) and data generated by your use of our services (browsing history, purchase history).",
      "We use this data to personalize your experience, process orders, and improve our services.",
      "We never sell your personal data to third parties. We may share data with trusted partners who help us operate our platform.",
      "You can access, update, or delete your personal data at any time through your account settings.",
      "Last updated: March 2026.",
    ],
  },
  terms: {
    title: "Terms of Service",
    content: [
      "By using ShopSmart, you agree to the following terms and conditions.",
      "You must be at least 18 years old to make purchases on our platform.",
      "All product listings, prices, and availability are subject to change without notice.",
      "ShopSmart reserves the right to cancel orders due to pricing errors, stock issues, or suspected fraud.",
      "Users are responsible for maintaining the confidentiality of their account credentials.",
      "For the full terms, contact legal@shopsmart.com.",
      "Last updated: March 2026.",
    ],
  },
  cookies: {
    title: "Cookie Policy",
    content: [
      "ShopSmart uses cookies to enhance your browsing experience.",
      "Essential cookies are required for core functionality like authentication and cart management.",
      "Analytics cookies help us understand how you use our site so we can improve it.",
      "Marketing cookies allow us to show you relevant ads and offers.",
      "You can manage your cookie preferences in your browser settings at any time.",
    ],
  },
  "payment-security": {
    title: "Payment Security",
    content: [
      "Your payment information is always safe with ShopSmart.",
      "We use industry-standard SSL/TLS encryption to protect all transactions.",
      "We are PCI DSS Level 1 compliant — the highest level of payment security certification.",
      "We never store your full credit card number on our servers.",
      "If you notice any unauthorized activity, contact us immediately at security@shopsmart.com.",
    ],
  },
  accessibility: {
    title: "Accessibility",
    content: [
      "ShopSmart is committed to making our platform accessible to everyone.",
      "We follow WCAG 2.1 AA guidelines to ensure our site is usable by people with disabilities.",
      "Features include: keyboard navigation, screen reader support, sufficient color contrast, and resizable text.",
      "If you encounter any accessibility barriers, please contact us at accessibility@shopsmart.com.",
    ],
  },
};

const StaticPage = () => {
  const { slug } = useParams<{ slug: string }>();
  const page = slug ? pages[slug] : null;

  if (!page) {
    return (
      <div className="container mx-auto flex min-h-[60vh] flex-col items-center justify-center px-4 py-16 text-center">
        <h1 className="text-4xl font-bold text-foreground">Page Not Found</h1>
        <p className="mt-2 text-muted-foreground">The page you're looking for doesn't exist.</p>
        <Link to="/" className="mt-6 text-sm font-medium text-accent hover:underline">
          ← Back to Home
        </Link>
      </div>
    );
  }

  return (
    <div className="container mx-auto max-w-3xl px-4 py-12">
      <Link to="/" className="mb-6 inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-accent transition-colors">
        <ArrowLeft className="h-4 w-4" /> Back to Home
      </Link>
      <h1 className="mb-6 text-3xl font-bold text-foreground">{page.title}</h1>
      <div className="space-y-4">
        {page.content.map((paragraph, i) => (
          <p key={i} className="text-muted-foreground leading-relaxed">{paragraph}</p>
        ))}
      </div>
    </div>
  );
};

export default StaticPage;
